# Generated by Django 2.1.1 on 2018-10-09 05:06

from django.db import migrations, models
import geoposition.fields
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('portada', sorl.thumbnail.fields.ImageField(upload_to='eventos/')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
