# Generated by Django 2.1.1 on 2018-11-10 04:14

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='position',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
