# Generated by Django 2.1.1 on 2018-11-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20181109_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
