# Generated by Django 2.1.1 on 2018-10-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Videotecas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cat', models.CharField(max_length=50, verbose_name='Codigo categoría')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('anio', models.CharField(max_length=50, verbose_name='Año')),
                ('apoyo', models.CharField(max_length=50, verbose_name='Apoyo de')),
                ('coleccion', models.CharField(max_length=250, verbose_name='Colección')),
                ('duracion', models.CharField(max_length=150, verbose_name='Duración')),
                ('edicion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Edición')),
                ('fotografia', models.CharField(max_length=250, verbose_name='Fotografía')),
                ('guion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Guión')),
                ('musica_original', models.CharField(blank=True, max_length=250, null=True, verbose_name='Música original')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pais_prod', models.CharField(blank=True, max_length=250, null=True, verbose_name='Pais de producción')),
                ('pais_ref', models.CharField(blank=True, max_length=250, null=True, verbose_name='Pais de referidos')),
                ('produccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Producción')),
                ('productora', models.CharField(max_length=250, verbose_name='Productora')),
                ('realizacion', models.CharField(max_length=250, verbose_name='Realización')),
                ('serie', models.CharField(max_length=250)),
                ('sintesis', models.TextField(verbose_name='Síntesis')),
                ('subtitulos', models.CharField(max_length=250, verbose_name='Subtítulos')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Generos')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Idiomas')),
                ('temas', models.ManyToManyField(blank=True, to='videoteca.Temas', verbose_name='Temas finales')),
            ],
            options={
                'verbose_name': 'Videoteca',
                'verbose_name_plural': 'Videotecas',
            },
        ),
    ]
