# Generated by Django 2.1.1 on 2018-11-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Colleción',
                'verbose_name_plural': 'Collecciones',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Videotecas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cat', models.CharField(max_length=50, verbose_name='Codigo categoría')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('duracion', models.CharField(max_length=150, verbose_name='Duración')),
                ('edicion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Edición')),
                ('fotografia', models.CharField(max_length=250, verbose_name='Fotografía')),
                ('guion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Guión')),
                ('musica_original', models.CharField(blank=True, max_length=250, null=True, verbose_name='Música original')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('produccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Producción')),
                ('productora', models.CharField(max_length=250, verbose_name='Productora')),
                ('realizacion', models.CharField(max_length=250, verbose_name='Realización')),
                ('sintesis', models.TextField(verbose_name='Síntesis')),
                ('subtitulos', models.CharField(max_length=250, verbose_name='Subtítulos')),
                ('url_video', models.URLField(blank=True, null=True)),
                ('imagen_portada', models.ImageField(upload_to='')),
                ('imagen_fill', models.ImageField(upload_to='')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Coleccion')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Generos')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Idiomas')),
                ('pais_prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_produccion', to='videoteca.Pais', verbose_name='Pais de producción')),
                ('pais_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_referidos', to='videoteca.Pais', verbose_name='Pais de referidos')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoteca.Series')),
                ('temas', models.ManyToManyField(blank=True, to='videoteca.Temas', verbose_name='Temas finales')),
            ],
            options={
                'verbose_name': 'Videoteca',
                'verbose_name_plural': 'Videotecas',
            },
        ),
    ]
