# Generated by Django 2.1.1 on 2018-10-29 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotecas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videotecas',
            name='slug',
            field=models.SlugField(editable=False, max_length=250),
        ),
    ]
