# Generated by Django 2.1.1 on 2018-11-21 21:30

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosCatalogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='catalogos/')),
            ],
            options={
                'verbose_name': 'Archivo para catálogo',
                'verbose_name_plural': 'Archivos para los catálogos',
            },
        ),
        migrations.CreateModel(
            name='CatalogosPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('portada', sorl.thumbnail.fields.ImageField(upload_to='colecciones/')),
                ('sinopsis', models.TextField()),
                ('year', models.CharField(max_length=20)),
                ('autores', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
            },
        ),
        migrations.CreateModel(
            name='GuiasDidacticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo de la guia')),
                ('guia', models.FileField(upload_to='guiasVideotecas/')),
            ],
            options={
                'verbose_name': 'Guia Didactica',
                'verbose_name_plural': 'Guias Didacticas',
            },
        ),
        migrations.AddField(
            model_name='archivoscatalogos',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.CatalogosPDF'),
        ),
    ]
