# Generated by Django 2.1.1 on 2018-11-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0002_auto_20181121_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiasdidacticas',
            name='archivo',
            field=models.FileField(default=None, upload_to='guiasVideotecas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guiasdidacticas',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Videotecas'),
        ),
    ]
