# Generated by Django 2.1.1 on 2019-03-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0003_auto_20181121_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotecas',
            name='anio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='videotecas',
            name='apoyo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Apoyo de'),
        ),
        migrations.AlterField(
            model_name='catalogospdf',
            name='year',
            field=models.CharField(max_length=20, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='videotecas',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoteca.Coleccion'),
        ),
        migrations.RemoveField(
            model_name='videotecas',
            name='pais_prod',
        ),
        migrations.AddField(
            model_name='videotecas',
            name='pais_prod',
            field=models.ManyToManyField(blank=True, null=True, related_name='pais_produccion', to='videoteca.Pais', verbose_name='Pais de producción'),
        ),
        migrations.RemoveField(
            model_name='videotecas',
            name='pais_ref',
        ),
        migrations.AddField(
            model_name='videotecas',
            name='pais_ref',
            field=models.ManyToManyField(blank=True, null=True, related_name='pais_referidos', to='videoteca.Pais', verbose_name='Pais de referidos'),
        ),
    ]
