# Generated by Django 2.1.1 on 2019-04-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0005_auto_20190307_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlacePublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('videoteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Videotecas')),
            ],
            options={
                'verbose_name': 'Enlace publicación',
                'verbose_name_plural': 'Enlaces publicaciones',
            },
        ),
        migrations.RemoveField(
            model_name='archivoscatalogos',
            name='catalogo',
        ),
        migrations.RemoveField(
            model_name='guiasdidacticas',
            name='guia',
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'ordering': ('nombre',), 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='idiomas',
            options={'ordering': ('nombre',), 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('nombre',), 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('nombre',), 'verbose_name': 'serie', 'verbose_name_plural': 'series'},
        ),
        migrations.DeleteModel(
            name='ArchivosCatalogos',
        ),
        migrations.DeleteModel(
            name='CatalogosPDF',
        ),
        migrations.DeleteModel(
            name='GuiasDidacticas',
        ),
    ]
