# Generated by Django 2.1.1 on 2019-04-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0006_auto_20190412_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoteca.Temas')),
            ],
            options={
                'verbose_name': 'Sub tema',
                'verbose_name_plural': 'Sub Temas',
            },
        ),
        migrations.AlterField(
            model_name='videotecas',
            name='temas',
            field=models.ManyToManyField(blank=True, to='videoteca.Temas', verbose_name='Temas principales'),
        ),
        migrations.AddField(
            model_name='videotecas',
            name='subtema',
            field=models.ManyToManyField(blank=True, to='videoteca.SubTemas', verbose_name='Temas secundarios'),
        ),
    ]
