# Generated by Django 2.1.1 on 2019-04-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0007_auto_20190418_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtemas',
            options={'ordering': ['-id'], 'verbose_name': 'Sub tema', 'verbose_name_plural': 'Sub Temas'},
        ),
        migrations.AlterModelOptions(
            name='temas',
            options={'ordering': ['-id'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
