# Generated by Django 2.1.1 on 2019-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0008_auto_20190421_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotecas',
            options={'ordering': ['-id'], 'verbose_name': 'Videoteca', 'verbose_name_plural': 'Videotecas'},
        ),
        migrations.AddField(
            model_name='enlacepublicacion',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
