# Generated by Django 2.1.1 on 2018-11-19 00:39

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLuciernaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=250)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='personal/')),
                ('cargo', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Personal de Luciérnaga',
            },
        ),
    ]
