# Generated by Django 2.1.1 on 2018-09-26 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temas',
            options={'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, max_length=250),
            preserve_default=False,
        ),
    ]
