# Generated by Django 2.1.1 on 2018-11-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosSecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(verbose_name='url de la seccion')),
                ('foto', models.FileField(upload_to='fotosecciones/')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.SiteConfiguration')),
            ],
            options={
                'verbose_name': 'Foto de sección',
                'verbose_name_plural': 'Fotos de las secciones',
            },
        ),
    ]
