# Generated by Django 2.1.1 on 2018-11-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20181115_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaSecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.SiteConfiguration')),
            ],
        ),
    ]
