# Generated by Django 2.1.1 on 2019-04-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_acercasecciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acercasecciones',
            options={'verbose_name': 'Acerca de sección', 'verbose_name_plural': 'Acerca de secciones'},
        ),
    ]
